### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Jakecheslekov** [juancarlospaco/pyvoicechanger#7]
Hey, really cool-looking program you've got here! Unfortunately I'm unable to make it work..
I tried installing it with python2 and that didn't work, so I attempted python3 & that didn't work either. I installed the angler thing, I was getting an error about that at first but now its a different error.

Tried to run it with sudo too but that also didn't work.

Traceback (most recent call last):
  File "/usr/bin/pyvoicechanger.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyvoicechanger==1.0.0', 'pyvoicechanger.py')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/pyvoicechanger-1.0.0-py3.6.egg/EGG-INFO/scripts/pyvoicechanger.py", line 19, in <module>
  File "/usr/lib/python3.6/site-packages/anglerfish-3.0.0-py3.6.egg/anglerfish/__init__.py", line 51, in <module>
ImportError: cannot import name 'get_random_pasteldark_color'

I uninstalled it(from source), and then re-installed it with pip, now it does this

Traceback (most recent call last):
  File "/usr/bin/pyvoicechanger.py", line 19, in <module>
    from anglerfish import (check_encoding, make_logger, make_post_exec_msg,
  File "/usr/lib/python3.6/site-packages/anglerfish-3.0.0-py3.6.egg/anglerfish/__init__.py", line 51, in <module>
ImportError: cannot import name 'get_random_pasteldark_color'

**Comment by Jakecheslekov** [comment]
????

**Comment by Jakecheslekov** [comment]
With python3 from source instead of pip
Testing Terminal Colors...
                                                                                 
                                                                                 
                                                                                  

Unix SysLog Server trying to Log to SysLog: /dev/log 
Logger created with Log file at: /tmp/pyvoicechanger.log. 
PyVoiceChanger.1.0.0https://github.com/juancarlospaco/pyvoicechanger#pyvoicechanger 
Python 3.6.4 on Linux-4.14.12-2-ck-x86_64-with-glibc2.3.4. 
STDIN Encoding: UTF-8. 
STDERR Encoding: UTF-8. 
STDOUT Encoding:UTF-8 
Default Encoding: utf-8. 
FileSystem Encoding: utf-8. 
PYTHONIOENCODING Encoding: None. 
Process Name set to: pyvoicechanger. 
Creating Abstract UDP Socket Lock for Single Instance. 
Socket Lock for Single Instance: <socket.socket fd=8, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, laddr=b'\x00_pyvoicechanger__lock'>. 
Traceback (most recent call last):
  File "/usr/bin/pyvoicechanger.py", line 4, in <module>
    __import__('pkg_resources').run_script('pyvoicechanger==1.0.0', 'pyvoicechanger.py')
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/usr/lib/python3.6/site-packages/pyvoicechanger-1.0.0-py3.6.egg/EGG-INFO/scripts/pyvoicechanger.py", line 201, in <module>
  File "/usr/lib/python3.6/site-packages/pyvoicechanger-1.0.0-py3.6.egg/EGG-INFO/scripts/pyvoicechanger.py", line 187, in main
  File "/usr/lib/python3.6/site-packages/anglerfish/set_desktop_launcher.py", line 17, in set_desktop_launcher
    if not isinstance(str, app) or not isinstance(str, desktop_file_content):
TypeError: isinstance() arg 2 must be a type or tuple of types
Compressed Unused Old Rotated Python Logs since: ~2018-01-13 12:12:28-05:00.

**Comment by hypothermic** [comment]
@Jakecheslekov The error from your latest comment here can be fixed by editing `/usr/lib/python3.6/site-packages/anglerfish/set_desktop_launcher.py` and replacing line 17

> if not isinstance(str, app) or not isinstance(str, desktop_file_content):  

with  
> if not isinstance(app, str) or not isinstance(desktop_file_content, str):  

Source: #6 and https://github.com/juancarlospaco/anglerfish/pull/39
